services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_PORT=${NGINX_PORT:-80}
      - APP_HOST=app
      - APP_PORT=${APP_PORT:-3000}
      - NGINX_TIMEOUT=${NGINX_TIMEOUT:-86400}
    ports:
      - ${NGINX_PORT:-80}:${NGINX_PORT:-80}
    depends_on:
      - app
