services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_PORT=${APP_PORT:-3000}
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
