services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PORT=4000
      - VIRTUAL_PORT=4000
      - VIRTUAL_HOST=moncef.studio
      - LETSENCRYPT_HOST=moncef.studio
      - LETSENCRYPT_EMAIL=moncef.hassani03@gmail.com
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
